### ISSUE TITLE
mpd connection error.

### ISSUE THREAD

**Issue by maotora** [lucidstack/ctrlp-mpc.vim#4]
So i keep getting `mpd connection error.` I don't know what's wrong yet.

In my computer i have aliased mpc="mpc --port 6602 --host 127.0.0.1".
Could this cause the connection issues?

I checked your plugin file (not familiar with .viml) but i could see there was no connection attempts ( like port/host specifications, again i don't know how viml works).

I'm also using pathogen so i didn't include 

``` vim
 let g:ctrlp_extensions = ['buffertag', 'tag', 'line', 'dir', 'tmux', 'mpc'] " <- This line 
```

Thank you!

**Comment by lucidstack** [comment]
Hey there, thank you for using ctrlp-mpc! Sorry this too so long, but I've now added a `g:ctrlp_mpc_cmd` variable that you can override in your `.vimrc`, just like your alias! 

Just update `ctrlp-mpc`, add

```
let g:ctrlp_mpc_cmd = 'mpc --port 6602 --host 127.0.0.1'
```

to your `.vimrc`, and you should be good to go! 

Thanks for reporting this issue, and let me know if it works for you! 👋🏻

**Comment by maotora** [comment]
It works!
Thank you very much! :)
